### ISSUE TITLE
Is there any place to download the compiled assets?

### ISSUE THREAD

**Issue by silvioprog** [Karlson2k/libmicrohttpd#26]
Hey Team!

Is there any place [like this](https://github.com/Karlson2k/libmicrohttpd/releases/tag/v1.0.0) to download the assets for other systems other than Windows?

TIA for any help!

**Comment by Karlson2k** [comment]
Hi Silvio,

The W32 is an exception because it does not have native build tools and the same time binaries are compatible across various versions.
Other systems often have native build tools preinstalled (or easily installable) and do not maintain cross-version compatibility, so it would be needed to build the lib for every combination of the kernel and the environment (like C run-time lib). So for other systems build from source is assumed.
